name: Publish Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "vite-plugin-*" # Push events to matching vite-plugin-*, i.e. vite-plugin-(sugar)@1.0.0
      - "create-arca*" # Push events to matching create-arca*, i.e. create-arca@1.0.0
      - "ar-changelog*" # Push events to matching ar-changelog*, i.e. ar-changelog@1.0.0

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'Spencer17x/arca'
    runs-on: macos-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get pkgName for tag
        id: tag
        run: |
          # matching v2.0.0 / v2.0.0-beta.8 etc
          if [[ $GITHUB_REF_NAME =~ ^v.+ ]]; then
            pkgName="arca"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi
          echo "::set-output name=pkgName::$pkgName"

      - name: Build
        run: pnpm --filter ${{ steps.tag.outputs.pkgName }} run build

      - name: Publish package
        run: pnpm run ci-publish -- ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
